//Generated by Claude Opus 4.8 6-16-26

// File: CoilOptimizerEngine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace CoilOptimizer
{
    public class CoilOptimizerEngine
    {
        public event EventHandler<SolutionFoundEventArgs> BetterSolutionFound;

        private CancellationTokenSource _cts;
        private CuttingResult _best;
        private readonly object _lock = new object();

        public Task BackgroundTask { get; private set; }

        /// <summary>
        /// Returns a fast result immediately and continues searching for a better
        /// one in the background, raising BetterSolutionFound as improvements appear.
        /// </summary>
        public CuttingResult Optimize(OptimizationInput input,
                                      CancellationToken externalToken = default)
        {
            ValidateInput(input);

            _cts = CancellationTokenSource.CreateLinkedTokenSource(externalToken);
            var token = _cts.Token;

            var demand = BuildDemand(input.Parts);

            // ---- Phase 1: fast deterministic greedy ----
            var fast = Solve(demand, input, rng: null, greediness: 1.0);
            fast.IsFinal = false;
            _best = fast;

            // ---- Phase 2: async improvement ----
            BackgroundTask = Task.Run(() => ImproveLoop(demand, input, token), token);

            return fast;
        }

        public void Cancel() => _cts?.Cancel();

        // -----------------------------------------------------------------

        private void ImproveLoop(List<DemandItem> demand, OptimizationInput input,
                                 CancellationToken token)
        {
            var deadline = DateTime.UtcNow + input.Options.Timeout;
            var rng = new Random(12345);

            try
            {
                while (!token.IsCancellationRequested && DateTime.UtcNow < deadline)
                {
                    // Perturb selection greediness to explore alternative patterns.
                    double greediness = 0.55 + rng.NextDouble() * 0.4;
                    var candidate = Solve(demand, input, rng, greediness);
                    if (candidate == null) continue;

                    if (input.Options.AllowStacking)
                        candidate = TryStacking(candidate, input);

                    lock (_lock)
                    {
                        if (IsBetter(candidate, _best))
                        {
                            _best = candidate;
                            RaiseFound(candidate, isFinal: false);
                        }
                    }
                }
            }
            catch (OperationCanceledException) { /* expected */ }

            lock (_lock)
            {
                _best.IsFinal = true;
                RaiseFound(_best, isFinal: true);
            }
        }

        private void RaiseFound(CuttingResult result, bool isFinal)
        {
            BetterSolutionFound?.Invoke(this,
                new SolutionFoundEventArgs { Result = result, IsFinal = isFinal });
        }

        // ----------------------- core solver -----------------------------

        private CuttingResult Solve(List<DemandItem> demand, OptimizationInput input,
                                    Random rng, double greediness)
        {
            decimal coilWidth = input.Constraints.SheetWidthConstraint.Value;
            int maxStrips = input.Options.MaxKnives + 1;
            decimal scrapWidth = input.Options.ScrapWidth;

            // NOTE: no GroupBy(Length). Longest parts first so they anchor row length.
            var items = demand.OrderByDescending(d => d.Length)
                              .ThenByDescending(d => d.Width).ToList();
            decimal[] widths = items.Select(i => i.Width).ToArray();
            decimal[] lengths = items.Select(i => i.Length).ToArray();
            int[] remaining = items.Select(i => i.Quantity).ToArray();

            var patterns = new List<Pattern>();

            while (remaining.Any(r => r > 0))
            {
                var candidates = EnumeratePatterns(widths, remaining, coilWidth, maxStrips);
                if (candidates.Count == 0) break;

                int[] chosen = SelectPattern(candidates, widths, lengths,
                                             coilWidth, rng, greediness);

                int repeat = int.MaxValue;
                for (int i = 0; i < chosen.Length; i++)
                    if (chosen[i] > 0)
                        repeat = Math.Min(repeat, remaining[i] / chosen[i]);
                if (repeat < 1) repeat = 1;

                patterns.Add(BuildPattern(chosen, widths, lengths, repeat,
                                          coilWidth, scrapWidth));

                for (int i = 0; i < chosen.Length; i++)
                    remaining[i] -= chosen[i] * repeat;
            }

            // Validity guard: reject solutions that didn't satisfy demand.
            if (remaining.Any(r => r > 0))
                return null;

            return BuildResult(patterns, input);
        }
        /// <summary>
        /// Bounded-knapsack enumeration of feasible strip layouts (patterns).
        /// Bounded tightly by maxStrips, so the search space stays small.
        /// </summary>
        private List<int[]> EnumeratePatterns(decimal[] widths, int[] remaining,
                                              decimal coilWidth, int maxStrips)
        {
            var results = new List<int[]>();
            var current = new int[widths.Length];
            const int hardCap = 20000;

            void Recurse(int start, decimal usedWidth, int strips)
            {
                if (strips > 0)
                    results.Add((int[])current.Clone());

                if (results.Count >= hardCap || strips >= maxStrips) return;

                for (int i = start; i < widths.Length; i++)
                {
                    int byWidth = (int)((coilWidth - usedWidth) / widths[i]);
                    int max = Math.Min(byWidth,
                              Math.Min(remaining[i] - current[i], maxStrips - strips));
                    for (int c = 1; c <= max; c++)
                    {
                        current[i] += c;
                        Recurse(i + 1, usedWidth + c * widths[i], strips + c);
                        current[i] -= c;
                    }
                }
            }

            Recurse(0, 0m, 0);
            return results;
        }

        private int[] SelectPattern(List<int[]> candidates, decimal[] widths,
                                    decimal[] lengths, decimal coilWidth,
                                    Random rng, double greediness)
        {
            // Rank by AREA efficiency: part area / (coilWidth * rowLength).
            // This rewards beneficial stacking (filling leftover width with a
            // shorter part) while penalizing rows where the stacked length is wasteful.
            var ranked = candidates.Select(c =>
            {
                decimal rowLen = 0m, partArea = 0m;
                int strips = 0;
                for (int i = 0; i < c.Length; i++)
                {
                    if (c[i] == 0) continue;
                    strips += c[i];
                    if (lengths[i] > rowLen) rowLen = lengths[i];
                    partArea += c[i] * widths[i] * lengths[i];
                }
                decimal rowArea = coilWidth * rowLen;
                return new
                {
                    Counts = c,
                    Strips = strips,
                    Eff = rowArea > 0m ? partArea / rowArea : 0m
                };
            })
            .OrderByDescending(x => x.Eff)
            .ThenByDescending(x => x.Strips)
            .ToList();

            if (rng == null || greediness >= 0.999) return ranked[0].Counts;

            int window = Math.Max(1, (int)(ranked.Count * (1.0 - greediness)));
            window = Math.Min(window, ranked.Count);
            return ranked[rng.Next(window)].Counts;
        }

        private Pattern BuildPattern(int[] counts, decimal[] widths, decimal[] lengths,
                                     int repeat, decimal coilWidth, decimal scrapWidth)
        {
            decimal used = UsedWidth(counts, widths);
            int strips = counts.Sum();
            decimal fallOff = R4(coilWidth - used);

            decimal rowLen = 0m;
            int manualPerRow = 0;
            for (int i = 0; i < counts.Length; i++)
                if (counts[i] > 0 && lengths[i] > rowLen) rowLen = lengths[i];

            var p = new Pattern
            {
                Length = R4(rowLen),
                Cuts = strips,
                Repeat = repeat,
                UsedWidth = R4(used),
                FallOff = fallOff,
                FallOffIsScrap = fallOff > 0m && fallOff < scrapWidth,
                Knives = fallOff > 0.0001m ? strips : Math.Max(0, strips - 1)
            };

            for (int i = 0; i < counts.Length; i++)
            {
                if (counts[i] == 0) continue;
                // A stacked lane (part shorter than the row) needs one manual cut/row.
                if (lengths[i] < rowLen - 0.0001m) manualPerRow += counts[i];

                p.Parts.Add(new PartCut
                {
                    Width = R4(widths[i]),
                    Length = R4(lengths[i]),
                    Quantity = counts[i]
                });
            }
            p.ManualCuts = manualPerRow;   // per single repeat
            return p;
        }
        private CuttingResult BuildResult(List<Pattern> patterns, OptimizationInput input)
        {
            decimal coilWidth = input.Constraints.SheetWidthConstraint.Value;
            decimal totalLength = 0m, partsArea = 0m, reusableArea = 0m;
            int result_manual = 0;

            foreach (var p in patterns)
            {
                totalLength += p.Length * p.Repeat;
                result_manual += p.ManualCuts * p.Repeat;
                foreach (var part in p.Parts)
                    partsArea += part.Width * part.Length * part.Quantity * p.Repeat;
                if (!p.FallOffIsScrap && p.FallOff > 0m)
                    reusableArea += p.FallOff * p.Length * p.Repeat;
            }

            decimal coilArea = totalLength * coilWidth;
            decimal waste = coilArea - partsArea - reusableArea;
            if (waste < 0m) waste = 0m;

            var result = new CuttingResult
            {
                Patterns = patterns,
                TotalLength = R4(totalLength),
                TotalWaste = R4(waste),
                WastePercentage = coilArea > 0m ? R4(waste / coilArea * 100m) : 0m,
                PatternCount = patterns.Count,
                KnifeChanges = patterns.Count // each setup = knives home + reposition
            };
            result.Score = ComputeScore(result, input);
            return result;
        }

        private decimal ComputeScore(CuttingResult r, OptimizationInput input)
        {
            // Length is primary; knife changes converted to a length-equivalent cost.
            return r.TotalLength
                 + r.KnifeChanges * input.Options.KnifeChangeLengthEquivalent;
        }

        private bool IsBetter(CuttingResult a, CuttingResult b)
        {
            if (a == null) return false;
            if (b == null) return true;
            const decimal eps = 0.0001m;

            if (Math.Abs(a.TotalLength - b.TotalLength) > eps)
                return a.TotalLength < b.TotalLength;          // 1
            if (a.PatternCount != b.PatternCount)
                return a.PatternCount < b.PatternCount;        // 2
            if (a.TotalManualCuts != b.TotalManualCuts)
                return a.TotalManualCuts < b.TotalManualCuts;  // 3
            return a.TotalWaste < b.TotalWaste - eps;          // 4
        }

        // ----------------------- stacking hook ---------------------------

        /// <summary>
        /// EXTENSION POINT. Real stacking (mixing different part lengths in one
        /// knife setup, e.g. two 40" lanes alongside an 80" lane with a manual
        /// intermediate cut) belongs here. Currently a no-op pass-through so the
        /// core remains correct. Implement length-direction packing per lane,
        /// then add the manual-cut cost where lane lengths differ.
        /// </summary>
        private CuttingResult TryStacking(CuttingResult candidate, OptimizationInput input)
        {
            return candidate;
        }

        // ----------------------- helpers ---------------------------------

        private static decimal UsedWidth(int[] counts, decimal[] widths)
        {
            decimal sum = 0m;
            for (int i = 0; i < counts.Length; i++) sum += counts[i] * widths[i];
            return sum;
        }

        private List<DemandItem> BuildDemand(List<PartCut> parts)
        {
            return parts
                .GroupBy(p => new { p.Width, p.Length })
                .Select(g => new DemandItem
                {
                    Width = g.Key.Width,
                    Length = g.Key.Length,
                    Quantity = g.Sum(x => x.Quantity)
                })
                .ToList();
        }

        private void ValidateInput(OptimizationInput input)
        {
            if (input == null) throw new ArgumentNullException(nameof(input));
            decimal coilWidth = input.Constraints.SheetWidthConstraint.Value;
            if (coilWidth <= 0m)
                throw new ArgumentException("SheetWidthConstraint must be > 0.");
            foreach (var p in input.Parts)
            {
                if (p.Width > coilWidth)
                    throw new ArgumentException(
                        $"Part width {p.Width} exceeds coil width {coilWidth} " +
                        "(rotation not implemented).");
                if (p.Width <= 0m || p.Length <= 0m || p.Quantity <= 0)
                    throw new ArgumentException("Invalid part dimensions/quantity.");
            }
        }

        private static decimal R4(decimal v) =>
            Math.Round(v, 4, MidpointRounding.AwayFromZero);

        private class DemandItem
        {
            public decimal Width;
            public decimal Length;
            public int Quantity;
        }
    }
}