//Generated by Claude Opus 4.8 6-16-26

// File: Model.cs
using System;
using System.Collections.Generic;

namespace CoilOptimizer
{
    public class PartCut
    {
        public string Id { get; set; }
        public decimal Width { get; set; }
        public decimal Length { get; set; }
        public int Quantity { get; set; }
    }

    public class Constraint
    {
        public string Name { get; set; }
        public decimal Value { get; set; }
    }

    public class OptimizationConstraints
    {
        public Constraint SheetWidthConstraint { get; set; } =
            new Constraint { Name = "SheetWidth", Value = 0m };
        public Constraint MinPartWidthConstraint { get; set; } =
            new Constraint { Name = "MinPartWidth", Value = 0m };
        public Constraint MinOutsidePartWidthConstraint { get; set; } =
            new Constraint { Name = "MinOutsidePartWidth", Value = 0m };
        public Constraint MinPartHeightConstraint { get; set; } =
            new Constraint { Name = "MinPartHeight", Value = 0m };
    }

    public class OptimizationOptions
    {
        public int MaxKnives { get; set; } = 8;            // => MaxKnives + 1 strips
        public decimal ScrapWidth { get; set; } = 3.0m;    // fall-off below this = waste
        public bool AllowStacking { get; set; } = true;    // hook only (see TryStacking)
        public bool AllowRotation { get; set; } = false;   // not implemented
        public TimeSpan Timeout { get; set; } = TimeSpan.FromSeconds(1);

        // Tie-breaking: one knife change is "worth" this many inches of coil.
        // 0 => length is strictly primary, knife changes are pure tie-break.
        public decimal KnifeChangeLengthEquivalent { get; set; } = 0m;
    }

    public class OptimizationInput
    {
        public OptimizationConstraints Constraints { get; set; } =
            new OptimizationConstraints();
        public OptimizationOptions Options { get; set; } =
            new OptimizationOptions();
        public List<PartCut> Parts { get; set; } = new List<PartCut>();
    }

    public class Pattern
    {
        public decimal Length { get; set; }       // length consumed per single repeat
        public int Cuts { get; set; }             // number of strips (lanes) in this row
        public int Knives { get; set; }           // = Cuts, or Cuts-1 if no fall-off
        public int Repeat { get; set; }           // how many rows sheared at this setup
        public List<PartCut> Parts { get; set; } = new List<PartCut>(); // per single row
        public decimal UsedWidth { get; set; }
        public decimal FallOff { get; set; }
        public bool FallOffIsScrap { get; set; }
        public int ManualCuts { get; set; }
    }

    public class CuttingResult
    {
        public decimal TotalLength { get; set; }      // coil length consumed
        public decimal TotalWaste { get; set; }       // area
        public decimal WastePercentage { get; set; }
        public int PatternCount { get; set; }         // distinct knife setups
        public int KnifeChanges { get; set; }
        public List<Pattern> Patterns { get; set; } = new List<Pattern>();
        public bool IsFinal { get; set; }
        public decimal Score { get; set; }            // lower is better
        public int TotalManualCuts { get; set; }
    }

    public class SolutionFoundEventArgs : EventArgs
    {
        public CuttingResult Result { get; set; }
        public bool IsFinal { get; set; }
    }
}